//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProVision.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProVision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行采集图像.
        /// </summary>
        internal static string chs_BTN_ACQUIREIMAGE {
            get {
                return ResourceManager.GetString("chs_BTN_ACQUIREIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加标定方案.
        /// </summary>
        internal static string chs_BTN_ADDCALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("chs_BTN_ADDCALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闭合圆环.
        /// </summary>
        internal static string chs_BTN_ANNULUS {
            get {
                return ResourceManager.GetString("chs_BTN_ANNULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算标定结果.
        /// </summary>
        internal static string chs_BTN_CALCULATECALIBRATION {
            get {
                return ResourceManager.GetString("chs_BTN_CALCULATECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闭合圆形.
        /// </summary>
        internal static string chs_BTN_CIRCLE {
            get {
                return ResourceManager.GetString("chs_BTN_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有向圆弧.
        /// </summary>
        internal static string chs_BTN_CIRULARARC {
            get {
                return ResourceManager.GetString("chs_BTN_CIRULARARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除活动ROI.
        /// </summary>
        internal static string chs_BTN_DELETEACTIVEROI {
            get {
                return ResourceManager.GetString("chs_BTN_DELETEACTIVEROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除所有ROI.
        /// </summary>
        internal static string chs_BTN_DELETEALLROI {
            get {
                return ResourceManager.GetString("chs_BTN_DELETEALLROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出标定.
        /// </summary>
        internal static string chs_BTN_EXITCALIBRATION {
            get {
                return ResourceManager.GetString("chs_BTN_EXITCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矢量线段.
        /// </summary>
        internal static string chs_BTN_LINE {
            get {
                return ResourceManager.GetString("chs_BTN_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载图像.
        /// </summary>
        internal static string chs_BTN_LOADIMAGE {
            get {
                return ResourceManager.GetString("chs_BTN_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行匹配定位.
        /// </summary>
        internal static string chs_BTN_MATCHLOCATION {
            get {
                return ResourceManager.GetString("chs_BTN_MATCHLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 齐轴矩形.
        /// </summary>
        internal static string chs_BTN_RECTANGLE1 {
            get {
                return ResourceManager.GetString("chs_BTN_RECTANGLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仿射矩形.
        /// </summary>
        internal static string chs_BTN_RECTANGLE2 {
            get {
                return ResourceManager.GetString("chs_BTN_RECTANGLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置窗口.
        /// </summary>
        internal static string chs_BTN_RESETWINDOW {
            get {
                return ResourceManager.GetString("chs_BTN_RESETWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存标定方案.
        /// </summary>
        internal static string chs_BTN_SAVECALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("chs_BTN_SAVECALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置匹配模型.
        /// </summary>
        internal static string chs_BTN_SETMATCHMODEL {
            get {
                return ResourceManager.GetString("chs_BTN_SETMATCHMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具坐标偏移.
        /// </summary>
        internal static string chs_BTN_TOOLOFFSET {
            get {
                return ResourceManager.GetString("chs_BTN_TOOLOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证标定结果.
        /// </summary>
        internal static string chs_BTN_VARIFYCALIBRATION {
            get {
                return ResourceManager.GetString("chs_BTN_VARIFYCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用连续采集.
        /// </summary>
        internal static string chs_CHKB_ACQUIRECONTINUE {
            get {
                return ResourceManager.GetString("chs_CHKB_ACQUIRECONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用工具偏移.
        /// </summary>
        internal static string chs_CHKB_ENABLETOOLOFFSET {
            get {
                return ResourceManager.GetString("chs_CHKB_ENABLETOOLOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用定位十字.
        /// </summary>
        internal static string chs_CHKB_ENABLEVERIDYCROSS {
            get {
                return ResourceManager.GetString("chs_CHKB_ENABLEVERIDYCROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基于特点的标定.
        /// </summary>
        internal static string chs_FRM_CALIBRATEPOINTBASED {
            get {
                return ResourceManager.GetString("chs_FRM_CALIBRATEPOINTBASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI交互式操作.
        /// </summary>
        internal static string chs_FRM_INTERACTIVEROI {
            get {
                return ResourceManager.GetString("chs_FRM_INTERACTIVEROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标定结果.
        /// </summary>
        internal static string chs_GRPB_CALIBRATERESULT {
            get {
                return ResourceManager.GetString("chs_GRPB_CALIBRATERESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特征点类型.
        /// </summary>
        internal static string chs_GRPB_FEATUREPOINTTYPE {
            get {
                return ResourceManager.GetString("chs_GRPB_FEATUREPOINTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作功能.
        /// </summary>
        internal static string chs_GRPB_OPERATION {
            get {
                return ResourceManager.GetString("chs_GRPB_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 形状选项.
        /// </summary>
        internal static string chs_GRPB_SHAPEOPTION {
            get {
                return ResourceManager.GetString("chs_GRPB_SHAPEOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视图选项.
        /// </summary>
        internal static string chs_GRPB_VIEWOPTION {
            get {
                return ResourceManager.GetString("chs_GRPB_VIEWOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角步长.
        /// </summary>
        internal static string chs_LBL_ANGLESTEP {
            get {
                return ResourceManager.GetString("chs_LBL_ANGLESTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物理误差.
        /// </summary>
        internal static string chs_LBL_CALIBRATEPHYSICALERROR {
            get {
                return ResourceManager.GetString("chs_LBL_CALIBRATEPHYSICALERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 像素误差.
        /// </summary>
        internal static string chs_LBL_CALIBRATEPIXELERROR {
            get {
                return ResourceManager.GetString("chs_LBL_CALIBRATEPIXELERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斜切角(Theta).
        /// </summary>
        internal static string chs_LBL_CHAMFERANGLE {
            get {
                return ResourceManager.GetString("chs_LBL_CHAMFERANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圆上点1.
        /// </summary>
        internal static string chs_LBL_CIRCLEPOINT1 {
            get {
                return ResourceManager.GetString("chs_LBL_CIRCLEPOINT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圆上点2.
        /// </summary>
        internal static string chs_LBL_CIRCLEPOINT2 {
            get {
                return ResourceManager.GetString("chs_LBL_CIRCLEPOINT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圆上点3.
        /// </summary>
        internal static string chs_LBL_CIRCLEPOINT3 {
            get {
                return ResourceManager.GetString("chs_LBL_CIRCLEPOINT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机械坐标.
        /// </summary>
        internal static string chs_LBL_MECHCOORDPROMPT {
            get {
                return ResourceManager.GetString("chs_LBL_MECHCOORDPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 像素坐标.
        /// </summary>
        internal static string chs_LBL_PIXCOORDPROMPT {
            get {
                return ResourceManager.GetString("chs_LBL_PIXCOORDPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置步长.
        /// </summary>
        internal static string chs_LBL_POSITIONSTEP {
            get {
                return ResourceManager.GetString("chs_LBL_POSITIONSTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旋转角(Phi).
        /// </summary>
        internal static string chs_LBL_ROTATEANGLE {
            get {
                return ResourceManager.GetString("chs_LBL_ROTATEANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平缩放(Sx).
        /// </summary>
        internal static string chs_LBL_SCALEX {
            get {
                return ResourceManager.GetString("chs_LBL_SCALEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直缩放(Sy).
        /// </summary>
        internal static string chs_LBL_SCALEY {
            get {
                return ResourceManager.GetString("chs_LBL_SCALEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具偏移.
        /// </summary>
        internal static string chs_LBL_TOOLOFFSETPROMPT {
            get {
                return ResourceManager.GetString("chs_LBL_TOOLOFFSETPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平偏移(Tx).
        /// </summary>
        internal static string chs_LBL_TRANSLATEX {
            get {
                return ResourceManager.GetString("chs_LBL_TRANSLATEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直偏移(Ty).
        /// </summary>
        internal static string chs_LBL_TRANSLATEY {
            get {
                return ResourceManager.GetString("chs_LBL_TRANSLATEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十字Col.
        /// </summary>
        internal static string chs_LBL_VERIFYCROSSCOL {
            get {
                return ResourceManager.GetString("chs_LBL_VERIFYCROSSCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十字Row.
        /// </summary>
        internal static string chs_LBL_VERIFYCROSSROW {
            get {
                return ResourceManager.GetString("chs_LBL_VERIFYCROSSROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X坐标.
        /// </summary>
        internal static string chs_LBL_XPROMPT {
            get {
                return ResourceManager.GetString("chs_LBL_XPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y坐标.
        /// </summary>
        internal static string chs_LBL_YPROMPT {
            get {
                return ResourceManager.GetString("chs_LBL_YPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定式特征点.
        /// </summary>
        internal static string chs_RDBTN_FIXEDPOINT {
            get {
                return ResourceManager.GetString("chs_RDBTN_FIXEDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 局部放大.
        /// </summary>
        internal static string chs_RDBTN_MAGNIFY {
            get {
                return ResourceManager.GetString("chs_RDBTN_MAGNIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动式特征点.
        /// </summary>
        internal static string chs_RDBTN_MOBILEPOINT {
            get {
                return ResourceManager.GetString("chs_RDBTN_MOBILEPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动图形.
        /// </summary>
        internal static string chs_RDBTN_MOVE {
            get {
                return ResourceManager.GetString("chs_RDBTN_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复初态.
        /// </summary>
        internal static string chs_RDBTN_NONE {
            get {
                return ResourceManager.GetString("chs_RDBTN_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放图形.
        /// </summary>
        internal static string chs_RDBTN_ZOOM {
            get {
                return ResourceManager.GetString("chs_RDBTN_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcquireImage.
        /// </summary>
        internal static string en_BTN_ACQUIREIMAGE {
            get {
                return ResourceManager.GetString("en_BTN_ACQUIREIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCalbration.
        /// </summary>
        internal static string en_BTN_ADDCALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("en_BTN_ADDCALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulus.
        /// </summary>
        internal static string en_BTN_ANNULUS {
            get {
                return ResourceManager.GetString("en_BTN_ANNULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateCalibration.
        /// </summary>
        internal static string en_BTN_CALCULATECALIBRATION {
            get {
                return ResourceManager.GetString("en_BTN_CALCULATECALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string en_BTN_CIRCLE {
            get {
                return ResourceManager.GetString("en_BTN_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CircularArc.
        /// </summary>
        internal static string en_BTN_CIRULARARC {
            get {
                return ResourceManager.GetString("en_BTN_CIRULARARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ActiveROI.
        /// </summary>
        internal static string en_BTN_DELETEACTIVEROI {
            get {
                return ResourceManager.GetString("en_BTN_DELETEACTIVEROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete AllROI.
        /// </summary>
        internal static string en_BTN_DELETEALLROI {
            get {
                return ResourceManager.GetString("en_BTN_DELETEALLROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitCalibration.
        /// </summary>
        internal static string en_BTN_EXITCALIBRATION {
            get {
                return ResourceManager.GetString("en_BTN_EXITCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string en_BTN_LINE {
            get {
                return ResourceManager.GetString("en_BTN_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        internal static string en_BTN_LOADIMAGE {
            get {
                return ResourceManager.GetString("en_BTN_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocateByMacth.
        /// </summary>
        internal static string en_BTN_MATCHLOCATION {
            get {
                return ResourceManager.GetString("en_BTN_MATCHLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle1.
        /// </summary>
        internal static string en_BTN_RECTANGLE1 {
            get {
                return ResourceManager.GetString("en_BTN_RECTANGLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle2.
        /// </summary>
        internal static string en_BTN_RECTANGLE2 {
            get {
                return ResourceManager.GetString("en_BTN_RECTANGLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Window.
        /// </summary>
        internal static string en_BTN_RESETWINDOW {
            get {
                return ResourceManager.GetString("en_BTN_RESETWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveCalibration.
        /// </summary>
        internal static string en_BTN_SAVECALIBRATIONSOLUTION {
            get {
                return ResourceManager.GetString("en_BTN_SAVECALIBRATIONSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMacthModel.
        /// </summary>
        internal static string en_BTN_SETMATCHMODEL {
            get {
                return ResourceManager.GetString("en_BTN_SETMATCHMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolOffset.
        /// </summary>
        internal static string en_BTN_TOOLOFFSET {
            get {
                return ResourceManager.GetString("en_BTN_TOOLOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerifyCalibration.
        /// </summary>
        internal static string en_BTN_VARIFYCALIBRATION {
            get {
                return ResourceManager.GetString("en_BTN_VARIFYCALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinuousAcquisition.
        /// </summary>
        internal static string en_CHKB_ACQUIRECONTINUE {
            get {
                return ResourceManager.GetString("en_CHKB_ACQUIRECONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableOffset.
        /// </summary>
        internal static string en_CHKB_ENABLETOOLOFFSET {
            get {
                return ResourceManager.GetString("en_CHKB_ENABLETOOLOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableCross.
        /// </summary>
        internal static string en_CHKB_ENABLEVERIDYCROSS {
            get {
                return ResourceManager.GetString("en_CHKB_ENABLEVERIDYCROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibrationBasedOnPoint.
        /// </summary>
        internal static string en_FRM_CALIBRATEPOINTBASED {
            get {
                return ResourceManager.GetString("en_FRM_CALIBRATEPOINTBASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI Interactive.
        /// </summary>
        internal static string en_FRM_INTERACTIVEROI {
            get {
                return ResourceManager.GetString("en_FRM_INTERACTIVEROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibrationResult.
        /// </summary>
        internal static string en_GRPB_CALIBRATERESULT {
            get {
                return ResourceManager.GetString("en_GRPB_CALIBRATERESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeOfFeaturePoint.
        /// </summary>
        internal static string en_GRPB_FEATUREPOINTTYPE {
            get {
                return ResourceManager.GetString("en_GRPB_FEATUREPOINTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string en_GRPB_OPERATION {
            get {
                return ResourceManager.GetString("en_GRPB_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Option.
        /// </summary>
        internal static string en_GRPB_SHAPEOPTION {
            get {
                return ResourceManager.GetString("en_GRPB_SHAPEOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Option.
        /// </summary>
        internal static string en_GRPB_VIEWOPTION {
            get {
                return ResourceManager.GetString("en_GRPB_VIEWOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AngleStep.
        /// </summary>
        internal static string en_LBL_ANGLESTEP {
            get {
                return ResourceManager.GetString("en_LBL_ANGLESTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhysicalError.
        /// </summary>
        internal static string en_LBL_CALIBRATEPHYSICALERROR {
            get {
                return ResourceManager.GetString("en_LBL_CALIBRATEPHYSICALERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelError.
        /// </summary>
        internal static string en_LBL_CALIBRATEPIXELERROR {
            get {
                return ResourceManager.GetString("en_LBL_CALIBRATEPIXELERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle(Theta).
        /// </summary>
        internal static string en_LBL_CHAMFERANGLE {
            get {
                return ResourceManager.GetString("en_LBL_CHAMFERANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point1OnCircle.
        /// </summary>
        internal static string en_LBL_CIRCLEPOINT1 {
            get {
                return ResourceManager.GetString("en_LBL_CIRCLEPOINT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point2OnCircle.
        /// </summary>
        internal static string en_LBL_CIRCLEPOINT2 {
            get {
                return ResourceManager.GetString("en_LBL_CIRCLEPOINT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point3OnCircle.
        /// </summary>
        internal static string en_LBL_CIRCLEPOINT3 {
            get {
                return ResourceManager.GetString("en_LBL_CIRCLEPOINT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MechCoord.
        /// </summary>
        internal static string en_LBL_MECHCOORDPROMPT {
            get {
                return ResourceManager.GetString("en_LBL_MECHCOORDPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelCoord.
        /// </summary>
        internal static string en_LBL_PIXCOORDPROMPT {
            get {
                return ResourceManager.GetString("en_LBL_PIXCOORDPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionStep.
        /// </summary>
        internal static string en_LBL_POSITIONSTEP {
            get {
                return ResourceManager.GetString("en_LBL_POSITIONSTEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle(Phi).
        /// </summary>
        internal static string en_LBL_ROTATEANGLE {
            get {
                return ResourceManager.GetString("en_LBL_ROTATEANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleX.
        /// </summary>
        internal static string en_LBL_SCALEX {
            get {
                return ResourceManager.GetString("en_LBL_SCALEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScaleY.
        /// </summary>
        internal static string en_LBL_SCALEY {
            get {
                return ResourceManager.GetString("en_LBL_SCALEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolOffset.
        /// </summary>
        internal static string en_LBL_TOOLOFFSETPROMPT {
            get {
                return ResourceManager.GetString("en_LBL_TOOLOFFSETPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslateX.
        /// </summary>
        internal static string en_LBL_TRANSLATEX {
            get {
                return ResourceManager.GetString("en_LBL_TRANSLATEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslateY.
        /// </summary>
        internal static string en_LBL_TRANSLATEY {
            get {
                return ResourceManager.GetString("en_LBL_TRANSLATEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossCol.
        /// </summary>
        internal static string en_LBL_VERIFYCROSSCOL {
            get {
                return ResourceManager.GetString("en_LBL_VERIFYCROSSCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossRow.
        /// </summary>
        internal static string en_LBL_VERIFYCROSSROW {
            get {
                return ResourceManager.GetString("en_LBL_VERIFYCROSSROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XCoord.
        /// </summary>
        internal static string en_LBL_XPROMPT {
            get {
                return ResourceManager.GetString("en_LBL_XPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YCoord.
        /// </summary>
        internal static string en_LBL_YPROMPT {
            get {
                return ResourceManager.GetString("en_LBL_YPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedPoint.
        /// </summary>
        internal static string en_RDBTN_FIXEDPOINT {
            get {
                return ResourceManager.GetString("en_RDBTN_FIXEDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnify.
        /// </summary>
        internal static string en_RDBTN_MAGNIFY {
            get {
                return ResourceManager.GetString("en_RDBTN_MAGNIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePoint.
        /// </summary>
        internal static string en_RDBTN_MOBILEPOINT {
            get {
                return ResourceManager.GetString("en_RDBTN_MOBILEPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string en_RDBTN_MOVE {
            get {
                return ResourceManager.GetString("en_RDBTN_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string en_RDBTN_NONE {
            get {
                return ResourceManager.GetString("en_RDBTN_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string en_RDBTN_ZOOM {
            get {
                return ResourceManager.GetString("en_RDBTN_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] halcondotnet {
            get {
                object obj = ResourceManager.GetObject("halcondotnet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icn_Location {
            get {
                object obj = ResourceManager.GetObject("Icn_Location", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
